MonsterDefName = {}
MonsterDefName[1] = {name = '迪兰',}
MonsterDefName[2] = {name = '迪迪兰',}
MonsterDefName[3] = {name = '迪兰特',}
MonsterDefName[4] = {name = '休咻',}
MonsterDefName[5] = {name = '休伊尔',}
MonsterDefName[6] = {name = '休罗斯',}
MonsterDefName[7] = {name = '拉奥',}
MonsterDefName[8] = {name = '拉奥苗',}
MonsterDefName[9] = {name = '拉奥叶',}
MonsterDefName[10] = {name = '法拉',}
MonsterDefName[11] = {name = '法娜',}
MonsterDefName[12] = {name = '法伊娜',}
MonsterDefName[13] = {name = '小小葵',}
MonsterDefName[14] = {name = '呆呆葵',}
MonsterDefName[15] = {name = '笑笑葵',}
MonsterDefName[16] = {name = '布尔',}
MonsterDefName[17] = {name = '布鲁托',}
MonsterDefName[18] = {name = '小树根',}
MonsterDefName[19] = {name = '树根使者',}
MonsterDefName[28] = {name = '蓝喵',}
MonsterDefName[29] = {name = '蓝虎鲸',}
MonsterDefName[30] = {name = '阿卡',}
MonsterDefName[31] = {name = '阿卡纳斯',}
MonsterDefName[32] = {name = '尤尼',}
MonsterDefName[33] = {name = '乔尼',}
MonsterDefName[34] = {name = '小岩浮',}
MonsterDefName[35] = {name = '大角岩浮',}
MonsterDefName[36] = {name = '大将岩浮',}
MonsterDefName[37] = {name = '霍克',}
MonsterDefName[38] = {name = '霍克努尔',}
MonsterDefName[41] = {name = '水墨点点',}
MonsterDefName[42] = {name = '水墨飞马',}
MonsterDefName[49] = {name = '多摩',}
MonsterDefName[50] = {name = '多摩桑',}
MonsterDefName[51] = {name = '阿宝',}
MonsterDefName[52] = {name = '阿财',}
MonsterDefName[55] = {name = '麦麦籽',}
MonsterDefName[56] = {name = '麦麦头',}
MonsterDefName[57] = {name = '麦麦迪',}
MonsterDefName[58] = {name = '大耳猴',}
MonsterDefName[59] = {name = '拳套猴',}
MonsterDefName[60] = {name = '长臂猴',}
MonsterDefName[61] = {name = '晓月兔',}
MonsterDefName[62] = {name = '拂晓兔',}
MonsterDefName[67] = {name = '稚壳鸡',}
MonsterDefName[68] = {name = '酷壳鸡',}
MonsterDefName[69] = {name = '蛋壳鸡',}
MonsterDefName[72] = {name = '乌达',}
MonsterDefName[73] = {name = '乌古达',}
MonsterDefName[74] = {name = '达达',}
MonsterDefName[75] = {name = '达克尔',}
MonsterDefName[76] = {name = '达克拉尔',}
MonsterDefName[77] = {name = '齿轮鹰',}
MonsterDefName[78] = {name = '呆目齿轮鹰',}
MonsterDefName[79] = {name = '莫古',}
MonsterDefName[80] = {name = '巨锤莫古',}
MonsterDefName[81] = {name = '沙之鹤',}
MonsterDefName[82] = {name = '沙皇鸟',}
MonsterDefName[86] = {name = '三眼蝎',}
MonsterDefName[87] = {name = '三眼石蝎',}
MonsterDefName[90] = {name = '雷伊',}
MonsterDefName[91] = {name = '伊特',}
MonsterDefName[92] = {name = '风伊特',}
MonsterDefName[93] = {name = '电伊特',}
MonsterDefName[94] = {name = '冰伊特',}
MonsterDefName[95] = {name = '暗伊特',}
MonsterDefName[96] = {name = '光伊特',}
MonsterDefName[97] = {name = '飞伊特',}
MonsterDefName[98] = {name = '沙伊特',}
MonsterDefName[99] = {name = '虫伊特',}
MonsterDefName[100] = {name = '战伊特',}
MonsterDefName[111] = {name = '砂砂',}
MonsterDefName[112] = {name = '砂吉塔',}
MonsterDefName[113] = {name = '跳跳鼠',}
MonsterDefName[114] = {name = '蹦蹦鼠',}
MonsterDefName[117] = {name = '阿布',}
MonsterDefName[118] = {name = '阿布布',}
MonsterDefName[119] = {name = '豚豚',}
MonsterDefName[120] = {name = '冰湖豚',}
MonsterDefName[121] = {name = '冰川豚',}
MonsterDefName[124] = {name = '伊露',}
MonsterDefName[125] = {name = '伊露辛',}
MonsterDefName[126] = {name = '尼娅',}
MonsterDefName[127] = {name = '卡尼娅',}
MonsterDefName[133] = {name = '小结',}
MonsterDefName[134] = {name = '大关',}
MonsterDefName[138] = {name = '多利',}
MonsterDefName[139] = {name = '多普利',}
MonsterDefName[142] = {name = '荷玛',}
MonsterDefName[143] = {name = '荷依米',}
MonsterDefName[144] = {name = '乔巴',}
MonsterDefName[145] = {name = '托尼乔巴',}
MonsterDefName[149] = {name = '小巴',}
MonsterDefName[150] = {name = '巴图',}
MonsterDefName[156] = {name = '菲亚',}
MonsterDefName[157] = {name = '菲亚斯',}
MonsterDefName[178] = {name = '米咔',}
MonsterDefName[194] = {name = '克里普',}
MonsterDefName[195] = {name = '克里普特',}
MonsterDefName[196] = {name = '艾萨',}
MonsterDefName[198] = {name = '泰姆',}
MonsterDefName[199] = {name = '泰姆尔',}
MonsterDefName[300] = {name = '小金',}
MonsterDefName[301] = {name = '金鳞',}
MonsterDefName[204] = {name = '芙拉',}
MonsterDefName[205] = {name = '芙拉伦斯',}
MonsterDefName[208] = {name = '安吉',}
MonsterDefName[209] = {name = '安吉丽塔',}
MonsterDefName[210] = {name = '弗格',}
MonsterDefName[211] = {name = '弗格斯',}
MonsterDefName[269] = {name = '莱卡',}
MonsterDefName[270] = {name = '莱卡斯',}
MonsterDefName[271] = {name = '莱卡斯昂',}
MonsterDefName[212] = {name = '石像鬼',}
MonsterDefName[213] = {name = '石像魔',}
MonsterDefName[214] = {name = '艾希',}
MonsterDefName[215] = {name = '艾丽希斯',}
MonsterDefName[222] = {name = '维维',}
MonsterDefName[223] = {name = '维克多',}
MonsterDefName[259] = {name = '英菲',}
MonsterDefName[260] = {name = '英菲迪',}
MonsterDefName[261] = {name = '英菲尼迪',}
MonsterDefName[302] = {name = '雷伊',}
MonsterDefName[364] = {name = '锦鲤',}
MonsterDefName[365] = {name = '鲤鱼王',}
MonsterDefName[361] = {name = '泰格',}
MonsterDefName[362] = {name = '泰格尔',}
MonsterDefName[363] = {name = '泰格伍茨',}
MonsterDefName[404] = {name = '萌犸',}
MonsterDefName[405] = {name = '猛犸象',}
MonsterDefName[495] = {name = '盖亚',}
MonsterDefName[1000] = {name = '库贝多',}
MonsterDefName[1001] = {name = '库贝勒',}
MonsterDefName[1002] = {name = '库贝萨',}
MonsterDefName[379] = {name = '萨菲',}
MonsterDefName[380] = {name = '萨隆',}
MonsterDefName[381] = {name = '萨菲隆',}
MonsterDefName[245] = {name = '缇姆',}
MonsterDefName[246] = {name = '斯缇姆',}
MonsterDefName[402] = {name = '小绿蜓',}
MonsterDefName[403] = {name = '彩翼蜓',}
MonsterDefName[262] = {name = '卜古',}
MonsterDefName[263] = {name = '卜古塔',}
MonsterDefName[280] = {name = '南瓜',}
MonsterDefName[281] = {name = '南瓜怪',}
MonsterDefName[3001] = {name = '莱卡斯昂',}
